### ISSUE TITLE
Error - must be of the type integer, float returned

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-webperf#12]
I have craft install with webperf. I recently imported DB and installed it on xampp localhost. When i try to open control panel, i get this error:

`Return value of nystudio107\webperf\recommendations\MemoryLimit::memoryLimit() must be of the type integer, float returned`

This is my composer file:
https://pastebin.com/RuTwzMji

**Comment by khalwat** [comment]
So I think the problem here is just that you've got Webperf pinned at a really old version -- this issue has been fixed.

Your `composer.json` has:

```
    "nystudio107/craft-webperf": "1.0.1",
```

This will cause Webperf to never get updated beyond 1.0.1 unless you do your updates via the Craft CP. Change it to:

```
    "nystudio107/craft-webperf": "^1.0.1",
```

...and then do ```
composer update
```

...and away you go.
