### ISSUE TITLE
WebPerf Plugin slowed site

### ISSUE THREAD

**Issue by mzlock** [nystudio107/craft-webperf#13]
Sorry for the vague bug report... I'll try to give you the most information I can...

We added WebPerf to a site and about a day after installing and enabling the plugin, the site got reeeeeally slow. The homepage was taking a good 10seconds to load - and that's not one of our possibly problematic pages that we brought WebPerf in to diagnose. Once I disabled WebPerf, the site snapped back to its normal speeds. The admin panel stayed fast even when the front-end of the site was slow.

Settings I had enabled:
- Include Browser Beacon: **On**
- Include Craft Beacon: **On**
- Static Cached Site: **On** (We're using Incapsula)
- WebPageTest.org API Key: Empty
- Webperf Data Samples to Store: bumped that down a tad to 10,000
- All other settings default

Other Plugins Installed:
- Asset Rev
- Cache Flag
- Rackspace Cloud Files (moving them to AWS soon)
- Redactor
- Reroute
- SuperTable
- Tags
- Video Embed
- Recaptcha
- a couple more home-coded plugins for this site to integrate with some 3rd-party services. One does do a fairly heavy query for related content, but even pages that don't use that plugin were very slow

Is there anything obvious that I set up incorrectly? Or any log files I should be looking at?

Craft version: 3.0.26.1 (This is further behind than I thought! Scheduling an upgrade night with them now)
plugin version: 1.0.7

**Comment by khalwat** [comment]
It'd be really strange for Webperf to affect the performance of your website _at all_. I think something else is afoot here.

I realize that uninstalling it you say brought things back to normal but... let's talk about your environment.

Try disabling just the Craft beacon, and see if things perform better. Then try disabling just the Browser beacon, and see if things perform better.

One thing I've seen in load balanced environments is that if there isn't cache coherency, that can cause problems. Have your devops folks look into that as well?

**Comment by mzlock** [comment]
@khalwat - thank you for getting back to me! Sorry I didn't post more info earlier; I know the information I gave wasn't really the whole picture. And this had to be dropped for a bit for other priorities...

I'll try your suggestions for turning the plugin back on, but disabling some settings. It'll just have to wait until traffic drops in the evening, but I'll test this tonight. And I'll keep an eye on some logs while I have it back on, so that hopefully I can give you some better information. Unfortunately, this isn't happening on Staging, so I have to be a bit careful.

This environment is not load-balanced; we just have one server with Incapsula in front of it. I'll try to tap the client's devops team too to see if they can assist.

**Comment by khalwat** [comment]
See the reason I'm a little confused is on the frontend, all it does is include some JavaScript that is loaded via async frame... and that won't impact anything per-wise. It's specifically engineered by the [Boomerang JS](https://developer.akamai.com/tools/boomerang/docs/index.html) folks not to.

When that beacon fires, it will send a request to a Webperf controller, but we have a rate limit in place so that we can't get oversaturated with requests:

https://github.com/nystudio107/craft-webperf/blob/v1/src/controllers/MetricsController.php#L198

So it shouldn't record any information more often than every 500ms, and when it does record information, it's a single fairly performant db write.

I'd be really interested in hearing what you find out re: toggling the various settings, and their impact.

**Comment by khalwat** [comment]
@mzlock any word on this?

**Comment by raptureaid** [comment]
We noticed similar a similar slow down after having WebPerf installed and running for some time. We found that eventually the samples delete query would run almost constantly, take a long time to complete and consume a bunch of the DB cycles for the server.

Rather than leave WebPerf to always run, we transitioned to turning it on for data collection sprints then disabling it while we review the data.

**Comment by khalwat** [comment]
@raptureaid what I'd suggest in that case is that you disable **Automatically Trim Data Samples** and instead run the console command via `cron` on a regular basis to clean it up:

https://github.com/nystudio107/craft-webperf#console-command

```bash
vagrant@homestead ~/sites/craft3 $ ./craft webperf/samples/trim 
Trimming data samples
Trimmed 503 from webperf_data_samples table
Trimming error samples
Trimmed 22 from webperf_error_samples table
```

Though I will say that this makes me think that the trimming should never run more than once per hour or maybe even once per day regardless.

https://github.com/nystudio107/craft-webperf/issues/16

**Comment by khalwat** [comment]
@raptureaid @mzlock Please check out version 1.0.9:

https://github.com/nystudio107/craft-webperf/releases/tag/1.0.9

## 1.0.9 - 2018.05.01
### Changed
* Removed vestigial debugging code
* Added a Sample Trimming Rate Limit that defaults to once per hour, to prevent the sample trimming from impacting performance

**Comment by khalwat** [comment]
I will re-open the issue if there is more information made available

**Comment by mzlock** [comment]
@khalwat and @raptureaid - thank you so much for all of this. Sorry this dropped off with some competing priorities and some travel time. I'll try out the new plugin version!

**Comment by khalwat** [comment]
No worries, I know how it is! If you have any further problems or performance concerns, please let me know! It's one of my missions to ensure that Webperf has minimal impact on its host.
