### ISSUE TITLE
Boomerang error on frontend

### ISSUE THREAD

**Issue by wihodges** [nystudio107/craft-webperf#20]
Getting a strange craft error:

<img width="614" alt="Screenshot 2019-06-24 11 30 15" src="https://user-images.githubusercontent.com/286956/60035960-b72b8980-9673-11e9-9d40-5aff94a7474e.png">

It's odd b/c it's picking up some text from h1 tag in the site ['Powering Brand']. This H1 tag is a bit different in that I have applied some js fittext that applies some styling to font size. But oddly it's not erroring on every page that I apply that the fittext call.

**Comment by khalwat** [comment]
Right so the reason it's erroring is that Webperf will minimize its code if `devMode` is not on.

What I think is probably happening is that I'm not escaping the config parameters for a JavaScript context, so if you have certain characters in the `title` it could cause this error.

Fixed in https://github.com/nystudio107/craft-webperf/commit/19dabc5c6114fdf5fbee8f06d095bda53491d07e
