### ISSUE TITLE
Crash in CP + errors in logs

### ISSUE THREAD

**Issue by daniellelecomte** [nystudio107/craft-webperf#24]
Hey there Andrew,

Seeing the same few errors often in the logs after trying to access the WebPerf dashboard in Craft. Dashboard crashes after attempting to load for several minutes. Memory limit is 512M on the server droplet.

Errors are as follows...

`2020-05-07 16:03:35 [-][-][-][error][nystudio107\webperf\services\DataSamples::addDataSample] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction`

`2020-05-05 17:58:23 [-][-][-][error][nystudio107\webperf\services\DataSamples::addDataSample] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction`

Craft CMS 3.4.7.1
Webperf 1.0.17

Thanks!

**Comment by daniellelecomte** [comment]
@khalwat - dude... any reply to this? It's been almost a month.

**Comment by khalwat** [comment]
@daniellelecomte apologies, I'm not sure how I didn't see this.

So it's possible for this error to happen, and what it means is that the db is busy doing something else when we're trying to record the data sample.

We catch the error, and log it -- but all it means is that a data sample didn't get recorded -> https://github.com/nystudio107/craft-webperf/blob/v1/src/services/DataSamples.php#L181

Feel free to reach out to me on Discord if you want to do a screen share, but this isn't a hard error.

**Comment by khalwat** [comment]
For high traffic sites, what I suggest doing is turning off **Automatically Trim Data Samples** and just running the console command to trim the samples from the CLI via cron -> https://nystudio107.com/docs/webperf/Using.html#console-command

It's possible that the automatically trimming of statistics on each data sample recording is what is causing this. It can happen on a high traffic site.

But again, this is a soft error. It just means a data sample couldn't get recorded because another process has the table locked.
